Require veloxide
Set FontFamily "JetBrains Mono"
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1800
Set Height 900

# Type a command in the terminal.
Type "veloxide init"

Enter

Sleep 1000ms

Type "my-demo-app"

Sleep 1000ms
Enter

# Say yes to having a frontend
Sleep 2000ms
Enter

# Select SvelteKit
Sleep 2000ms
Enter

# Admire the output for a bit.
Sleep 8s
